# Generated by Django 4.2 on 2024-06-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles'),
        ),
    ]
